### ISSUE TITLE
Clarification on required IP addresses and network service policy changes for Single Node CVO.

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/bluexp-cloud-volumes-ontap#332] opened 2024-08-07 19:18 UTC
### Page URL

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html

### Page title

Create data-serving storage VMs for Cloud Volumes ONTAP in Azure

### Summary

To provide clarity of the required IP addresses of a single node CVO.

Please add the following information under this section: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html#single-node-system: 

You'll need to create the following IP addresses:

    One IP address for iSCSI data LIF access.

    One IP address for NAS data LIF access.

    An optional IP address for a storage VM (SVM) management LIF

    This management LIF provides a connection to management tools like SnapCenter.

Also, please add the steps for the necessary changes to the network service policies to the single node CVO.  The current way our documentation reads, makes it seem like those steps are only required for CVO HA. 

 Please see screenshot:

![image](https://github.com/user-attachments/assets/53577417-dd65-4c84-854f-fd9d9f544580)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment] 2024-08-08 03:26
Thank you @virtualhawk for adding this issue. We will look into it and update this thread when the issue is resolved.

**Comment by netapp-manini** [comment] 2024-09-12 15:43
The filer confirmed that this issue is redundant for single nodes. Closing.

**Closed by netapp-manini** 2024-09-12 15:43 UTC
